spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: none
        show_sql: false
  datasource:
    primary:
      url: "jdbc:postgresql://localhost:5432/flight_control_db"
      username: "db_user"
      password: "pluto2000"
      schema: public
      hikari:
        maximumPoolSize: 10
        poolName: "primary-pool"
    liquibase:
      url: "jdbc:postgresql://localhost:5432/flight_control_db"
      username: "db_user"
      password: "pluto2000"
      schema: public
      change-log: classpath:/db/changelog/db.changelog-master.yaml
      hikari:
        maximumPoolSize: 1
        poolName: "liquibase-pool"

logging:
  level:
    root: INFO







