version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres:12
    env_file:
      - postgres-database.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data: